### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by juhoaj** [larenala/Pizzapalvelu#1]
Ladattu arvioitavaksi 26.2. klo 20

## Yleistä

Sovelluksen koodi on selkeää ja sitä on ilo lukea! On hienoa kuinka suurin osa viewsin routeista on toteutettu napakasti vähillä riveillä. Tilauslomakkeen routet ovat aika pitkiä mutta tarjoavat toiminnallisuuksiä jotka tekevät tilauslomakkeesta todella mukavan käyttää. Todella hieno idea ohjata käyttäjä menuun kun tilauslomakkeelta on poistettu kaikki pizzat! Lisäksi on hauska että etusivuun on panostettu.

## Muutama konkreettinen kehitysidea:

* Pizzan syöttämisessä muutaman validaattorin virheviesteihin kannattaa vielä kiinnittää huomiota. Nyt esim. Url:n validoinnin virheilmoitus ei näkynyt käyttöliittymässä
* Käyttöliittymän navigaatiota voisi kenties vielä viritellä. “View order” sekä “Order history” -linkkien piilottaminen kirjautumattomilta käyttäjiltä iffittämällä esim. kurssimateriaalin 5.3. esimerkin tyylillä tekisi navista käytettävämmän. Ja toki Admin-menun piilottaminen muilta kuin admin-käyttäjiltä olisi myös kiva lisä eikä “Register a new user” -linkkiä kenties tarvitse näyttää kirjautuneille käyttäjille?
* Tietokantakaaviossa on vielä listattuna “Juoma” ja “TilausJuoma” jotka voisi kenties poistaa tai merkitä erikseen jatkokehityksessä lisättäviksi. 
* Paginaation lisäämistä voisi harkita tilaukset ja käyttäjät listaavaan näkymään sekä kenties myös asiakkaan tilauksiin. Omassa projektissani onnistui verrattain kivuttomasti tuolla Flask-laajennuksella https://pythonhosted.org/Flask-paginate/
* ordes:n formissa jäi hieaman auki mihin items:iä käytetään. Jos tarkoituksena on lisätä /orders -näkymään sarake tietoa varten niin olisiko hyvä käyttää räätälöityä kutsua?

Dokumentaatiossa on useampi käyttäjätarina joita ei vielä ole toteutettu. Jos ne eivät ole työn alla loppurutistuksessa ne ehkä kannattaisi siivota erilliselle jatkokehityslistalle:
* “As a user I want to add new fillings to the pizza I have chosen, so I can customise it to my taste”
* “As a user, I want to modify or cancel my order afterwards, so that I can change my mind” 
* “As a user I can see the discounts, if any, on the bill, so that I know I’ve been charged right”
* “As an admin, I can create regular discounts without manually changing the price each time, so that I can have lunch discounts”

**Comment by larenala** [comment]
Moi! Kiitos palautteesta, annoit paljon hyviä huomioita mihin panostaa loppuvaiheessa. Mukavaa kevään jatkoa :)
